/// Equipment model that matches the backend schema.
/// Each equipment now has a unique ID for individual tracking.
class Equipment {
  final String? id;
  final String uniqueId;  // Unique ID like "WH-001", "WH-002"
  final String serialNo;  // Base serial number (e.g., "WH")
  final String name;
  final int quantity;     // Always 1 for individual items
  final String purchasedFrom;
  final String place;
  final String phone;
  final String status;    // 'available', 'supplied', 'maintenance'
  final DateTime? createdAt;

  const Equipment({
    this.id,
    required this.uniqueId,
    required this.serialNo,
    required this.name,
    required this.quantity,
    required this.purchasedFrom,
    required this.place,
    required this.phone,
    this.status = 'available',
    this.createdAt,
  });

  /// Create Equipment from JSON (API response).
  factory Equipment.fromJson(Map<String, dynamic> json) {
    return Equipment(
      id: json['id']?.toString() ?? json['_id']?.toString(),
      uniqueId: json['uniqueId']?.toString() ?? '',
      serialNo: json['serialNo']?.toString() ?? '',
      name: json['name']?.toString() ?? '',
      quantity: (json['quantity'] is int)
          ? json['quantity'] as int
          : int.tryParse(json['quantity']?.toString() ?? '1') ?? 1,
      purchasedFrom: json['purchasedFrom']?.toString() ?? '',
      place: json['place']?.toString() ?? '',
      phone: json['phone']?.toString() ?? '',
      status: json['status']?.toString() ?? 'available',
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'].toString())
          : null,
    );
  }

  /// Convert Equipment to JSON for API requests.
  /// Note: Does not include uniqueId as it's auto-generated by the server.
  Map<String, dynamic> toJson() {
    return {
      'serialNo': serialNo,
      'name': name,
      'quantity': quantity,
      'purchasedFrom': purchasedFrom,
      'place': place,
      'phone': phone,
    };
  }

  /// Create a copy with updated fields.
  Equipment copyWith({
    String? id,
    String? uniqueId,
    String? serialNo,
    String? name,
    int? quantity,
    String? purchasedFrom,
    String? place,
    String? phone,
    String? status,
  }) {
    return Equipment(
      id: id ?? this.id,
      uniqueId: uniqueId ?? this.uniqueId,
      serialNo: serialNo ?? this.serialNo,
      name: name ?? this.name,
      quantity: quantity ?? this.quantity,
      purchasedFrom: purchasedFrom ?? this.purchasedFrom,
      place: place ?? this.place,
      phone: phone ?? this.phone,
      status: status ?? this.status,
      createdAt: createdAt,
    );
  }

  /// Check if equipment is available for supply
  bool get isAvailable => status == 'available';

  /// Get status color for UI
  String get statusLabel {
    switch (status) {
      case 'available':
        return 'Available';
      case 'supplied':
        return 'Supplied';
      case 'maintenance':
        return 'Maintenance';
      default:
        return status;
    }
  }

  @override
  String toString() {
    return 'Equipment(uniqueId: $uniqueId, name: $name, status: $status)';
  }
}
